version: '3.8'

services:
  db:
    image: postgres:13
    container_name: equipment_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: equipment_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SEED_TEST_DATA: ${SEED_TEST_DATA}
    ports:
      - "8080:${SERVER_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: equipment_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
